-- MySQL Script generated by MySQL Workbench
-- Thu Oct 16 12:38:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema se
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema se
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `se` DEFAULT CHARACTER SET utf8mb3 ;
USE `se` ;

-- -----------------------------------------------------
-- Table `se`.`kjoretoy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `se`.`kjoretoy` ;

CREATE TABLE IF NOT EXISTS `se`.`kjoretoy` (
  `kjoretoy_id` INT NOT NULL AUTO_INCREMENT,
  `kjoretoy_navn` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`kjoretoy_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `se`.`rute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `se`.`rute` ;

CREATE TABLE IF NOT EXISTS `se`.`rute` (
  `rute_id` INT NOT NULL AUTO_INCREMENT,
  `rute_navn` VARCHAR(45) NULL DEFAULT NULL,
  `kjoretoy_id` INT NOT NULL,
  PRIMARY KEY (`rute_id`),
  INDEX `fk_rute_kjoretoy1_idx` (`kjoretoy_id` ASC) VISIBLE,
  CONSTRAINT `fk_rute_kjoretoy1`
    FOREIGN KEY (`kjoretoy_id`)
    REFERENCES `se`.`kjoretoy` (`kjoretoy_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `se`.`stoppested`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `se`.`stoppested` ;

CREATE TABLE IF NOT EXISTS `se`.`stoppested` (
  `stoppested_id` INT NOT NULL AUTO_INCREMENT,
  `sted_navn` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`stoppested_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `se`.`stoppested_has_rute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `se`.`stoppested_has_rute` ;

CREATE TABLE IF NOT EXISTS `se`.`stoppested_has_rute` (
  `stoppested_id` INT NOT NULL,
  `rute_id` INT NOT NULL,
  `rekkefolge` INT NULL DEFAULT NULL,
  PRIMARY KEY (`stoppested_id`, `rute_id`),
  INDEX `fk_stoppested_has_rute_rute1_idx` (`rute_id` ASC) VISIBLE,
  INDEX `fk_stoppested_has_rute_stoppested_idx` (`stoppested_id` ASC) VISIBLE,
  CONSTRAINT `fk_stoppested_has_rute_rute1`
    FOREIGN KEY (`rute_id`)
    REFERENCES `se`.`rute` (`rute_id`),
  CONSTRAINT `fk_stoppested_has_rute_stoppested`
    FOREIGN KEY (`stoppested_id`)
    REFERENCES `se`.`stoppested` (`stoppested_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



